version: '3.8'

services:

  db:
    image: postgres:17.5-alpine3.21
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

volumes:
  postgres_data:
  pgadmin-data:
