version: '3.8'

services:

  db:
    image: postgres:17.5-alpine3.21
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db_dump:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=chinook
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

  pgadmin:
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin-data:
